steps:
  # Build the Docker image
  - id: "Build Docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "STRIPE_PUBLIC_KEY=${_STRIPE_PUBLIC_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${_NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}"
      - "--build-arg"
      - "NEXT_PUBLIC_CLOUDINARY_API_KEY=${_NEXT_PUBLIC_CLOUDINARY_API_KEY}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA"
      - "."

  # Push the image to Artifact Registry
  - id: "Push Docker image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA"

  # Deploy the image to Cloud Run
  - id: "Deploy to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_CLOUD_RUN_SERVICE}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--quiet"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _AR_REPOSITORY: "edura"
  _IMAGE_NAME: "edura-website"
  _CLOUD_RUN_SERVICE: "edura-website"

  _STRIPE_PUBLIC_KEY: ""
  _NEXT_PUBLIC_BASE_URL: ""
  _NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ""
  _NEXT_PUBLIC_CLOUDINARY_API_KEY: ""
