steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "STRIPE_PUBLIC_KEY=${_STRIPE_PUBLIC_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}"
      - "--build-arg"
      - "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${_NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}"
      - "--build-arg"
      - "NEXT_PUBLIC_CLOUDINARY_API_KEY=${_NEXT_PUBLIC_CLOUDINARY_API_KEY}"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/edura/edura-website:$COMMIT_SHA"
      - "."

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/edura/edura-website:$COMMIT_SHA"

  # Deploy the container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "edura-website"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/edura/edura-website:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/edura/edura-website:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _STRIPE_PUBLIC_KEY: ""
  _NEXT_PUBLIC_BASE_URL: ""
  _NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ""
  _NEXT_PUBLIC_CLOUDINARY_API_KEY: ""
